from enum import Enum

class AuthPermEnum(Enum):
     # USER PERMISSIONS
     USER_CREATE = 'USER_CREATE'
     USER_UPDATE = 'USER_UPDATE'
     USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
     USER_DELETE = 'USER_DELETE'
     USER_LIST = 'USER_LIST'
     USER_DETAILS = 'USER_DETAILS'


     STUDENT_CREATE = 'STUDENT_CREATE'
     STUDENT_UPDATE = 'STUDENT_UPDATE'
     STUDENT_DELETE = 'STUDENT_DELETE'
     STUDENT_LIST = 'STUDENT_LIST'
     STUDENT_DETAILS = 'STUDENT_DETAILS'

     # PERMISSION PERMISSIONS
     PERMISSION_CREATE = 'PERMISSION_CREATE'
     PERMISSION_UPDATE = 'PERMISSION_UPDATE'
     PERMISSION_PARTIAL_UPDATE = 'PERMISSION_PARTIAL_UPDATE'
     PERMISSION_DELETE = 'PERMISSION_DELETE'
     PERMISSION_LIST = 'PERMISSION_LIST'
     PERMISSION_DETAILS = 'PERMISSION_DETAILS'

     # ROLE PERMISSION
     ROLE_CREATE = 'ROLE_CREATE'
     ROLE_UPDATE = 'ROLE_UPDATE'
     ROLE_DELETE = 'ROLE_DELETE'
     ROLE_LIST = 'ROLE_LIST'
     ROLE_DETAILS = 'ROLE_DETAILS'



class PermissionEnum(Enum):

     USER_CREATE = 'USER_CREATE'
     USER_UPDATE = 'USER_UPDATE'
     USER_PARTIAL_UPDATE = 'USER_PARTIAL_UPDATE'
     USER_DELETE = 'USER_DELETE'
     USER_LIST = 'USER_LIST'
     USER_DETAILS = 'USER_DETAILS'

    # PERMISSION ENUM

     TEXT_BOOK_CREATE = 'TEXT_BOOK_CREATE'
     TEXT_BOOK_UPDATE = 'TEXT_BOOK_UPDATE'
     TEXT_BOOK_DELETE = 'TEXT_BOOK_DELETE'
     TEXT_BOOK_LIST = 'TEXT_BOOK_LIST'
     TEXT_BOOK_DETAILS = 'TEXT_BOOK_DETAILS'


     SCHOOL_SUBSCRIPTION_CREATE = 'SCHOOL_SUBSCRIPTION_CREATE'
     SCHOOL_SUBSCRIPTION_UPDATE = 'SCHOOL_SUBSCRIPTION_UPDATE'
     SCHOOL_SUBSCRIPTION_DELETE = 'SCHOOL_SUBSCRIPTION_DELETE'
     SCHOOL_SUBSCRIPTION_LIST = 'SCHOOL_SUBSCRIPTION_LIST'
     SCHOOL_SUBSCRIPTION_DETAILS = 'SCHOOL_SUBSCRIPTION_DETAILS'



